CRITICAL - 2023-11-09 09:53:01 --> Too few arguments to function CodeIgniter\Router\RouteCollection::get(), 1 passed in /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Config/Routes.php on line 8 and at least 2 expected
in SYSTEMPATH/Router/RouteCollection.php on line 1016.
 1 APPPATH/Config/Routes.php(8): CodeIgniter\Router\RouteCollection->get()
 2 SYSTEMPATH/Router/RouteCollection.php(344): require('/home/2023DIFAL3/e22109603/public_html/V1/ci/app/Config/Routes.php')
 3 SYSTEMPATH/CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 4 SYSTEMPATH/CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt()
 5 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-09 09:53:01 --> Uncaught ErrorException: chmod() has been disabled for security reasons in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Log/Handlers/FileHandler.php:119
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Log/Handlers/FileHandler.php(119): chmod()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Log/Logger.php(294): CodeIgniter\Log\Handlers\FileHandler->handle()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Common.php(810): CodeIgniter\Log\Logger->log()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Debug/Exceptions.php(133): log_message()
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler()
#6 {main}
  thrown
【Previous Exception】
ArgumentCountError
Too few arguments to function CodeIgniter\Router\RouteCollection::get(), 1 passed in /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Config/Routes.php on line 8 and at least 2 expected
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Config/Routes.php(8): CodeIgniter\Router\RouteCollection->get()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Router/RouteCollection.php(344): require('/home/2023DIFAL...')
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#6 {main}
in SYSTEMPATH/Log/Handlers/FileHandler.php on line 119.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-09 09:53:26 --> Too few arguments to function CodeIgniter\Router\RouteCollection::get(), 1 passed in /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Config/Routes.php on line 8 and at least 2 expected
in SYSTEMPATH/Router/RouteCollection.php on line 1016.
 1 APPPATH/Config/Routes.php(8): CodeIgniter\Router\RouteCollection->get()
 2 SYSTEMPATH/Router/RouteCollection.php(344): require('/home/2023DIFAL3/e22109603/public_html/V1/ci/app/Config/Routes.php')
 3 SYSTEMPATH/CodeIgniter.php(810): CodeIgniter\Router\RouteCollection->loadRoutes()
 4 SYSTEMPATH/CodeIgniter.php(450): CodeIgniter\CodeIgniter->tryToRouteIt()
 5 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-09 10:30:54 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'e22109603sql'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:185
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php(185): mysqli->real_connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-11-09 10:30:54 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Compte->lister()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-09 10:34:58 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'e22109603sql'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:185
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php(185): mysqli->real_connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-11-09 10:34:58 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Compte->lister()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-09 10:35:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'e22109603sql'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:185
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php(185): mysqli->real_connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-11-09 10:35:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Compte->lister()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-09 10:35:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'e22109603sql'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:185
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php(185): mysqli->real_connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-11-09 10:35:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Compte->lister()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-09 10:35:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'e22109603sql'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:185
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php(185): mysqli->real_connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-11-09 10:35:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Compte->lister()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-09 10:37:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'e22109603sql'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:185
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php(185): mysqli->real_connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-11-09 10:37:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Compte->lister()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-09 10:37:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'e22109603sql'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:185
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php(185): mysqli->real_connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#8 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
#3 /home/2023DIFAL3/e22109603/public_html/V1/ci/app/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
#4 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(942): App\Controllers\Compte->lister()
#5 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 /home/2023DIFAL3/e22109603/public_html/V1/ci/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 /home/2023DIFAL3/e22109603/public_html/V1/ci/public/index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-11-09 10:37:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH/Models/Db_model.php(15): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Compte.php(15): App\Models\Db_model->get_all_compte()
 4 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Compte->lister()
 5 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 7 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-09 10:56:48 --> syntax error, unexpected '<', expecting end of file
in APPPATH/Models/Db_model.php on line 19.
 1 SYSTEMPATH/Autoloader/Autoloader.php(291): CodeIgniter\Autoloader\Autoloader->includeFile()
 2 SYSTEMPATH/Autoloader/Autoloader.php(269): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass()
 4 [internal function]: spl_autoload_call()
 5 SYSTEMPATH/Config/Factories.php(283): class_exists()
 6 SYSTEMPATH/Config/Factories.php(202): CodeIgniter\Config\Factories::locateClass()
 7 SYSTEMPATH/Config/Factories.php(161): CodeIgniter\Config\Factories::getDefinedInstance()
 8 SYSTEMPATH/Common.php(827): CodeIgniter\Config\Factories::__callStatic()
 9 APPPATH/Controllers/Actualite.php(13): model()
10 SYSTEMPATH/CodeIgniter.php(942): App\Controllers\Actualite->afficher()
11 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
12 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
13 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
